/** Mirrors `KERNEL_CHANNELS` in `src/electron/ipc/validate.ts`. */
export const KERNEL_IPC_CHANNELS = [
  'applyWindowSettings',
  'getConfig',
  'getDefaultThemeName',
  'getExtensionSettingsSchemas',
  'getExtensionTranslations',
  'getIcon',
  'getIconPack',
  'getPreloads',
  'getTheme',
  'getThemeByName',
  'getToolElementTag',
  'installExtension',
  'listCompositionSlots',
  'listIconPacks',
  'listInstalledExtensions',
  'listOrchestrators',
  'listProviders',
  'listSystemFonts',
  'listThemes',
  'listTools',
  'listUikitExtensions',
  'setExtensionEnabled',
  'uninstallExtension',
  'validateCompositionClaim',
] as const
